package edu.uiowa.osandvold.makeuppercasetext;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

public class ConvertToUppercase extends AppCompatActivity {
    // Define View Objects
    private Button cnvtButton;
    private EditText inputText;
    private EditText outputText;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // r is the autogenerated input that is similar to an index at the back of the book
        setContentView(R.layout.activity_convert_to_uppercase);

        // bind view to objects
        cnvtButton = (Button) findViewById(R.id.convertButton);
        inputText = (EditText) findViewById(R.id.inputText);
        outputText = (EditText) findViewById(R.id.outputText);

        cnvtButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String input = inputText.getText().toString();
                outputText.setText(input.toUpperCase());
            }
        });
    }

}
